#! /bin/sh

module load python3/3.5.2
module load hdf5/1.8.10
module load gdal/2.1.3
module load netcdf
module unload openmpi
module load openmpi/1.10.7

unset PYTHONPATH

# Set PYTHONPATH to wherever additional packages are stored

export PYTHONPATH=/short/er4/awracms/.pypackages

